version: '3.6'
services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:latest
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://192.168.0.6'
        unicorn['worker_timeout'] = 60
        unicorn['worker_processes'] = 2
        unicorn['port'] = 9090
        letsencrypt['enable'] = false
        nginx['redirect_http_to_https'] = true
        nginx['ssl_certificate'] = "/etc/gitlab/ssl/gitlab.pem"
        nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/gitlab.key"
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.exmail.qq.com"
        gitlab_rails['smtp_port'] = 25
        gitlab_rails['smtp_user_name'] = "zqlee@ronghui.tech"
        gitlab_rails['smtp_password'] = "****************"
        gitlab_rails['smtp_domain'] = "exmail.qq.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = false
        gitlab_rails['smtp_tls'] = false
        gitlab_rails['smtp_openssl_verify_mode'] = 'none'
        gitlab_rails['gitlab_email_enabled'] = true
        gitlab_rails['gitlab_email_from'] = 'zqlee@ronghui.tech'
        gitlab_rails['gitlab_email_display_name'] = 'noreply@ronghui.tech'
        alertmanager['admin_email'] = "zqlee@ronghui.tech"
    ports:
      - "80:80"
      - "443:443"
      - "2224:22"
    volumes:
      - "./config:/etc/gitlab"
      - "./logs:/var/log/gitlab"
      - "./data:/var/opt/gitlab"
